### ISSUE TITLE
csi2022 Data

### ISSUE THREAD

**Issue by Mjvolk3** [samgoldman97/mist#2]
If we would like to rebuild that csi2022 data to do some benchmarking, what is the best way to go about this? After getting the necessary licensing for NIST20 I'd like make sure our dataset will be as similar to csi2022 as possible. Thanks for any recommendations.

**Comment by samgoldman97** [comment]
Hi Michael, 
Excited to see follow your up work on this! Kai Dührkop assembled the dataset (using the datasets outlined in their CANOPUS publication such as MassBank, GNPS, and NIST20). He may be able to share the same files with you directly. In the event this is not possible, I've just pushed the names of all the spectra and exact splits I used, which should be consistent with their ID's in the respective databases.

Best,
Sam
